<a href="https://colab.research.google.com/github/KodumuruRaja/Instance-Based-Algorithms/blob/main/Self-Organizing-Map-(SOM).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.spatial import distance
np.set_printoptions(suppress=True) #Force-Supress all exponential notation
k=2
p=0
alpha=0.7 #Initial Learning Rate
x=np.array([[1,1,0,0],
            [0,1,0,0],
            [0,0,1,0],
            [0,0,1,1]])
# Print the number of data and dimension
n=len(x)
d=len(x[0])
addZeros=np.zeros((n,1))
x=np.append(x,addZeros,axis=1)
print("The SOM algorithm: \n")
print("The training data: \n",x)
print("\nTotal number of data: ",n)
print("Total number of features: ",d)
print("Total number of Clusters: ",k)
#create an empty array of centers
C=np.zeros((k,d+1))
#Randomly initalize the weight matrix
weight=np.random.rand(n,k)
print("\nThe initial weight: \n", np.round(weight,2))
for it in range(100): # Total number of iterations
     for i in range(n):
        distMin = 99999999
        for j in range(k):
            print("I J",i,j)
            dist = np.square(distance.euclidean(weight[:,j], x[i,0:d]))
            if distMin>dist:
                distMin = dist
                jMin = j
        print("jMin dist",jMin,dist)
        weight[:,jMin] = weight[:,jMin]*(1-alpha) + alpha*x[i,0:d]   
        print(weight)
     alpha = 0.5*alpha
print("\nThe final weight: \n",np.round(weight,4))
for i in range(n):    
    cNumber = np.where(weight[i] == np.amax(weight[i]))
    x[i,d] = cNumber[0]
    print("\nThe data with cluster number: \n", x) 

The SOM algorithm: 

The training data: 
 [[1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0.]]

Total number of data:  4
Total number of features:  4
Total number of Clusters:  2

The initial weight: 
 [[0.57 0.66]
 [0.99 0.32]
 [0.   0.26]
 [0.85 0.71]]
I J 0 0
I J 0 1
jMin dist 0 1.1549514204377063
[[0.87029407 0.66424845]
 [0.99829013 0.31606033]
 [0.00080788 0.26339077]
 [0.2558618  0.71068569]]
I J 1 0
I J 1 1
jMin dist 0 1.4834483192528372
[[0.26108822 0.66424845]
 [0.99948704 0.31606033]
 [0.00024236 0.26339077]
 [0.07675854 0.71068569]]
I J 2 0
I J 2 1
jMin dist 1 1.5887874450614443
[[0.26108822 0.19927453]
 [0.99948704 0.0948181 ]
 [0.00024236 0.77901723]
 [0.07675854 0.21320571]]
I J 3 0
I J 3 1
jMin dist 1 0.7165794551106196
[[0.26108822 0.05978236]
 [0.99948704 0.02844543]
 [0.00024236 0.93370517]
 [0.07675854 0.76396171]]
I J 0 0
I J 0 1
jMin dist 0 3.2833703332272925
[[0.51970734 0.05978236]
 [0.99966657 0.02844543]
 [0.00015754 0.93370517]
 [0.0498930